---
- name: Set and sanitize facts
  ansible.builtin.include_tasks: facts.yml
  tags: phpversion

- name: Setup package repositories
  ansible.builtin.include_tasks: "packages/{{ ansible_os_family | lower }}.yml"
  tags: phpversion

- name: Remove PHP packages (if version changing)
  ansible.builtin.package:
    name: "{{ php_packages }}"
    state: absent
  when:
    - php_version_switch is defined
    - php_version_switch
  tags: phpversion

- name: Install PHP packages
  ansible.builtin.package:
    name: "{{ php_packages }}"
    state: present
  tags: phpversion

- name: Configure php.ini
  ansible.builtin.template:
    src: etc/php.ini.j2
    dest: "{{ php_config_ini_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart php-fpm
  tags: phpversion

- name: Configure rlimit_files in php-fpm.conf
  ansible.builtin.lineinfile:
    path: "{{ php_fpm_config_path }}"
    regexp: "^;rlimit_files.*"
    line: rlimit_files = {{ php_ini_rlimit_files }}
  notify: Restart php-fpm
  tags: phpversion

- name: Check if Apache dirs are present
  ansible.builtin.stat:
    path: "{{ apache_config_path }}"
  register: apache

- name: Configure Apache PHP settings
  ansible.builtin.template:
    src: etc/httpd/conf.d/php.conf.j2
    dest: "{{ apache_config_path }}/php.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart php-fpm
  when: apache.stat.exists

- name: Include systemd restart configuration
  ansible.builtin.include_tasks: systemd.yml
  when: >-
    ( php_systemd_restart|default(False)
    or systemd_restart|default(False) )
    and systemd_restart_setting is defined

- name: Start and enable php-fpm service
  ansible.builtin.service:
    name: "{{ php_fpm_daemon }}"
    state: started
    enabled: true
