---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache (on Debian).
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  vars:
    system_user: example
    site_domain: example.com
  roles:
    - role: ansible-role-php_fpm
