---
- name: (RedHat) Install repository management packages
  ansible.builtin.package:
    name:
      - epel-release
      - yum-utils
    state: present

- name: (RedHat) Add Remi repository GPG key
  ansible.builtin.rpm_key:
    state: present
    key: "https://rpms.remirepo.net/RPM-GPG-KEY-{{ target }}"
  vars:
    target: >-
      {{ "remi2021" if version | int == 9
      else ("remi2018" if version | int == 8
      else ("remi" if version | int == 7
      else "remi2023")) }}
    version: "{{ ansible_distribution_major_version }}"

- name: (RedHat) Add Remi repository
  ansible.builtin.package:
    name: https://rpms.remirepo.net/enterprise/remi-release-{{- ansible_distribution_major_version }}.rpm

# FIXME: Find a better way to enable a repo prior to installing packages
# FIXME: Idempotence is broken on this task. Anything we can hook onto?
- name: (RedHat) Disable current Remi PHP repository (if version changing)
  ansible.builtin.raw: "{{ command }}{{ target }}"
  changed_when: result.rc > 0
  register: result
  vars:
    command: >-
      {{ "yum-config-manager --disable remi-php" if version | int == 7
      else "dnf module enable -y php:remi-" }}
    target: >-
      {{ php_version_installed_flat if version | int == 7
      else php_version_installed }}
    version: "{{ ansible_distribution_major_version }}"
  when:
    - php_version_switch | default(false)
    - php_version_switch is defined

# FIXME: Find a better way to enable a repo prior to installing packages
# FIXME: Idempotence is broken on this task. Anything we can hook onto?
- name: (RedHat) Enable Remi PHP repository
  ansible.builtin.raw: "{{ command }}{{ target }}"
  changed_when: result.rc > 0
  register: result
  vars:
    command: >-
      {{ "yum-config-manager --enable remi-php" if version | int == 7
      else "dnf module enable -y php:remi-" }}
    target: >-
      {{ php_version_flat if version | int == 7
      else php_version }}
    version: "{{ ansible_distribution_major_version }}"
